version: 2
updates:
  - package-ecosystem: "github-actions"    
    # Wait 14 days before updating to help circumvent supply chain attacks
    cooldown:
      default-days: 14
    directory: "/"
    schedule:
      interval: weekly
      time: "07:00"
    open-pull-requests-limit: 10
