version: '2'
networks:
  gosamlserviceprovider:
    driver: bridge
services:
   keycloak-resources:
     image: build-keycloak-resources
     build:
       context: .
       dockerfile: Dockerfile-keycloak-resources
   mongo:
     image: mongo:3.3
     #ports:
     #  - 27017:27017
     networks:
       - gosamlserviceprovider
   keycloak:
     image: jboss/keycloak:8.0.1
     environment:
     #Set in the keycloak-add-user.json file
     #- KEYCLOAK_USER=keycloak
     #- KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/importrealms/realm-test.json
     volumes_from:
       - keycloak-resources:rw
     #ports:
     # - "8080:8080"
     networks:
       - gosamlserviceprovider
   echo:
     image: mendhak/http-https-echo
     networks:
       - gosamlserviceprovider

   
