version: '2'
networks:
  gosamlserviceprovider:
    driver: bridge
services:
   mongo:
     image: mongo:3.3
     ports:
       - 27017:27017
     networks:
       - gosamlserviceprovider
   keycloak:
     image: jboss/keycloak:8.0.1
     environment:
#      Set in the keycloak-add-user.json file
#      - KEYCLOAK_USER=keycloak
#      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/importrealms/realm-test.json
     volumes:
      - ./keycloak:/importrealms
      - ./keycloak/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
     ports:
      - "8080:8080"
     networks:
       - gosamlserviceprovider
   
