version: '2'
networks:
  gosamlserviceprovider:
    driver: bridge
services:
   mongo:
     image: mongo:3.3
     networks:
       - gosamlserviceprovider
   keycloak:
     image: jboss/keycloak:8.0.1
     environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/importrealms/realm-test.json
     volumes:
      - ./keycloak:/importrealms
      - ./keycloak/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
     ports:
      - "8080:8080"
     networks:
       - gosamlserviceprovider
   idp:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/simpleidp:216dc29366c81841266ee8ea7b44133d69bb10f9
     volumes:
      - ./citizenidp/cert:/cert
      - ./citizenidp/citizenidp-metadata:/metadata
      - ./citizenidp/userdb:/userdb
     environment:
      - IDP_CERTIFICATE=certificate.crt
      - IDP_PRIVATE_KEY=certificate.pem
      - IDP_ADMIN_PASSWORD=test123
      - IDP_TECHNICAL_EMAIL=eva@kvalitetsit.dk
      - IDP_SECRET_SALT=abcd23poiu
      - IDP_HOSTNAME=idp
      - IDP_CONTEXTPATH=citizenidp
      - IDP_PROTOCOL=http
#     ports:
#      - "8090:80"
     networks:
       - gosamlserviceprovider

