FROM alpine:3.10.3
RUN apk add --update --no-cache gettext
COPY ./caddy-templates/Caddyfile-saml /caddyfiletemplates/Caddyfile-saml
ENV SAML_CLIENT_LOGLEVEL info
ENV TEMPLATE_FILE /caddyfiletemplates/Caddyfile-saml
ENV CADDYFILE /config
ENV METRICS_PATH /metrics
RUN cat /caddyfiletemplates/Caddyfile-saml
ENTRYPOINT envsubst < ${TEMPLATE_FILE} > ${CADDYFILE}
