# We use the module we just built
FROM kvalitetsit/gosamlserviceprovider as caddybuilder
ENV GO111MODULE=on

# Prepare for custom caddy build
RUN mkdir /caddy
WORKDIR /caddy
ENV GOPRIVATE="github.com/KvalitetsIT"
COPY go-caddy.mod go.mod
RUN go mod download

# Kitcaddy module source
COPY caddy /caddy/
RUN go test caddy/samlmodule
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/caddy .

FROM scratch
COPY --from=caddybuilder /go/bin/caddy /usr/bin/caddy
ENTRYPOINT ["/usr/bin/caddy", "run"]
