FROM alpine:3.10.3
RUN apk add --update --no-cache gettext jq
COPY ./caddytemplates/caddyfiletemplates/Caddyfile-wsc /caddyfiletemplates/Caddyfile-wsc
COPY ./caddytemplates/caddyfiletemplates/Caddyfile-wsp /caddyfiletemplates/Caddyfile-wsp
COPY ./caddytemplates/caddyfiletemplates/Caddyfile-wsc-nosessiondata  /caddyfiletemplates/Caddyfile-wsc-nosessiondata
ENV WSC_CLIENT_LOGLEVEL info
ENV WSP_CLIENT_LOGLEVEL info
ENTRYPOINT envsubst < ${TEMPLATE_FILE} > ${CADDYFILE}
