apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: samltest
  name: samltest
  namespace: gosidecars
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: samltest
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: samltest
    spec:
      containers:
        - args:
            - -config
            - /config/caddy.conf
          image: kvalitetsit/caddysamlprovider:dev
          name: caddy-saml-proxy
          volumeMounts:
            - mountPath: /config
              name: caddy-config
            - mountPath: /tls
              name: tls-cert
              readOnly: true
          ports:
           - containerPort: 8443
             name: https-proxy
             protocol: TCP
        - image: mendhak/http-https-echo
          name: demo
      initContainers:
        - env:
            - name: CADDYFILE
              value: /config/caddy.conf
            - name: SAML_CLIENT_LOGLEVEL
              value: debug
            - name: LISTEN_PORT
              value: "8443"
            - name: MONGO_HOST
              value: mongo.default
            - name: MONGO_DATABASE
              value: samltest
            - name: SAML_SESSION_HEADER
              value: SESSIONSAMLTEST
            - name: SAML_AUDIENCE_RESTRICTION
              value: testsamlgo
            - name: SAML_IDP_METADATAURL
              value: https://telemed-medarbejderlogin-test.rm.dk/auth/realms/broker/protocol/saml/descriptor
            - name: SAML_ENTITY_ID
              value: testsamlgo
            - name: SAML_SIGN_AUTH_REQUEST
              value: "true"
            - name: SAML_SIGN_CERT_FILE
              value: /tls/tls.crt
            - name: SAML_SIGN_KEY_FILE
              value: /tls/tls.key
            - name: SAML_SESSION_EXPIRY_HOURS
              value: "6"
            - name: SAML_EXTERNAL_URL
              value: https://telemed-test.rm.dk/samltest
            - name: SAML_SLO_PATH
              value: /saml/SLO
            - name: SAML_SSO_PATH
              value: /saml/SSO
            - name: SAML_METADATA_PATH
              value: /saml/metadata
            - name: SAML_LOGOUT_PATH
              value: /saml/logout
            - name: SAML_COOKIE_PATH
              value: /samltest
            - name: SAML_COOKIE_DOMAIN
              value: telemed-test.rm.dk
            - name: SAML_BACKEND_HOST
              value: localhost
            - name: SAML_BACKEND_PORT
              value: "80"
          image: kvalitetsit/caddysamltemplates:dev
          name: caddy-config
          volumeMounts:
            - mountPath: /config
              name: caddy-config
      volumes:
        - name: tls-cert
          secret:
            defaultMode: 420
            secretName: samltest-certs
        - emptyDir: {}
          name: caddy-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: samltest
  namespace: gosidecars
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: telemed-test.rm.dk
      http:
        paths:
          - backend:
              serviceName: samltest
              servicePort: 8443
            path: /samltest/?(.*)
  tls:
    - hosts:
        - telemed-test.rm.dk
      secretName: sslcert
---
apiVersion: v1
kind: Service
metadata:
  name: samltest
  namespace: gosidecars
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https-proxy
  selector:
    app.kubernetes.io/instance: samltest
