apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: samltest
  name: samltest
  namespace: gosidecars
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: samltest
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: samltest
    spec:
      containers:
        - args:
            - -config
            - /config/caddy-saml.conf
          image: kvalitetsit/caddysamlprovider:dev
          name: caddy-saml-proxy
          volumeMounts:
            - mountPath: /config
              name: caddy-config
            - mountPath: /tls
              name: tls-cert
              readOnly: true
          ports:
            - containerPort: 8443
              name: https-proxy
              protocol: TCP
        - args:
            - -config
            - /config/caddy-wsc.conf
          image: kvalitetsit/gooioidwsrest:1.1.2j
          name: caddy-wsc
          volumeMounts:
            - mountPath: /config
              name: caddy-config
            - mountPath: /tls
              name: tls-cert
              readOnly: true
            - mountPath: /sts
              name: sts-cert-volume
              readOnly: true
        - env:
           - name: ENDPOINTS
             value: http://localhost:8383
           - name: PORT
             value: "8787"
          image: kvalitetsit/echoconsumer:d1cbc994d4db00c89ead4d240950c2990e078f32
          imagePullPolicy: Always
          name: demo
      initContainers:
        - env:
            - name: CADDYFILE
              value: /config/caddy-saml.conf
            - name: SAML_CLIENT_LOGLEVEL
              value: debug
            - name: LISTEN_PORT
              value: "8383"
            - name: MONGO_HOST
              value: mongo.default
            - name: MONGO_DATABASE
              value: samltest
            - name: SAML_SESSION_HEADER
              value: SESSIONSAMLTEST
            - name: SAML_AUDIENCE_RESTRICTION
              value: testsamlgo
            - name: SAML_IDP_METADATAURL
              value: https://telemed-medarbejderlogin-test.rm.dk/auth/realms/broker/protocol/saml/descriptor
            - name: SAML_ENTITY_ID
              value: testsamlgo
            - name: SAML_SIGN_AUTH_REQUEST
              value: "true"
            - name: SAML_SIGN_CERT_FILE
              value: /tls/tls.crt
            - name: SAML_SIGN_KEY_FILE
              value: /tls/tls.key
            - name: SAML_SESSION_EXPIRY_HOURS
              value: "6"
            - name: SAML_EXTERNAL_URL
              value: https://telemed-test.rm.dk/samltest
            - name: SAML_SLO_PATH
              value: /saml/SLO
            - name: SAML_SSO_PATH
              value: /saml/SSO
            - name: SAML_METADATA_PATH
              value: /saml/metadata
            - name: SAML_LOGOUT_PATH
              value: /saml/logout
            - name: SAML_COOKIE_PATH
              value: /samltest
            - name: SAML_COOKIE_DOMAIN
              value: telemed-test.rm.dk
            - name: SAML_BACKEND_HOST
              value: localhost
            - name: SAML_BACKEND_PORT
              value: "80"
          image: kvalitetsit/caddysamltemplates:dev
          name: caddy-config
          volumeMounts:
            - mountPath: /config
              name: caddy-config
        - env:
          - name: TEMPLATE_FILE
            value: /caddyfiletemplates/Caddyfile-wsc
          - name: CADDYFILE
            value: /config/caddy-wsc.conf
          - name: LISTEN_PORT
            value: "8383"
          - name: MONGO_HOST
            value: mongo.default
          - name: MONGO_DATABASE
            value: gosidecars_wsc
          - name: WSC_STS_URL
            value: https://sts.test-vdxapi.vconf.dk/sts/service/sts //TODO
          - name: WSC_SERVICE_AUDIENCE
            value: urn:medcom:videoapi
          - name: WSC_CLIENT_CERTIFICATE_FILE
            value: /tls/tls.crt
          - name: WSC_CLIENT_KEY_FILE
            value: /tls/tls.key
          - name: WSC_SERVICE_ENDPOINT_HOST
            value: wspdemo1.test01.kitkube.dk
          - name: WSC_SERVICE_ENDPOINT_PORT
            value: "443"
          - name: WSC_SERVICE_ENDPOINT_CONTEXT
          - name: WSC_SESSION_DATA_URL
            value: http://localhost:8443/getsessiondata
          - name: WSC_TRUST_CERT_FILES
            value: '"/sts/tls.crt","/sts/tls.crt"'
          - name: WSC_CLIENT_LOGLEVEL
            value: debug
          image: kvalitetsit/gooioidwsrest-templates:1.1.2j
          imagePullPolicy: IfNotPresent
          name: caddy-config
          volumeMounts:
            - mountPath: /config
              name: caddy-config
      volumes:
        - name: tls-cert
          secret:
            defaultMode: 420
            secretName: samltest-certs
        - emptyDir: {}
          name: caddy-config
        - name: sts-cert-volume
          secret:
            secretName: sts-public-cert
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: gowsp
  name: gowsp
  namespace: gosidecars
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/instance: gowsp
    template:
      metadata:
        labels:
          app.kubernetes.io/instance: gowsp
      spec:
        containers:
          - args:
              - -config
              - /config/caddy.conf
            image: kvalitetsit/gooioidwsrest:1.1.2j
            name: caddy-proxy
            ports:
              - containerPort: 8443
                name: https-proxy
                protocol: TCP
            volumeMounts:
              - mountPath: /config
                name: caddy-config
              - mountPath: /tls
                name: tls-cert
                readOnly: true
              - mountPath: /sts
                name: sts-cert-volume
                readOnly: true
          - image: mendhak/http-https-echo:latest
            imagePullPolicy: Always
            name: echo
            ports:
              - containerPort: 80
                name: http
                protocol: TCP
        initContainers:
          - env:
              - name: TEMPLATE_FILE
                value: /caddyfiletemplates/Caddyfile-wsp
              - name: CADDYFILE
                value: /config/caddy.conf
              - name: LISTEN_PORT
                value: "8443"
              - name: MONGO_HOST
                value: mongo.default
              - name: MONGO_DATABASE
                value: gosidecars_wsp
              - name: SSL_HOST_NAME
                value: wspdemo1.test01.kitkube.dk //TODO
              - name: WSP_SSL_CERTIFICATE_FILE
                value: /tls/tls.crt
              - name: WSP_SSL_KEY_FILE
                value: /tls/tls.key
              - name: WSP_BACKEND_HOST
                value: localhost
              - name: WSP_BACKEND_PORT
                value: "80"
              - name: WSP_AUDIENCE_RESTRICTION
                value: urn:medcom:videoapi //TODO
              - name: WSP_TRUST_CERT_FILES
                value: '"/sts/tls.crt"'
              - name: WSP_CLIENT_LOGLEVEL
                value: debug
            image: kvalitetsit/gooioidwsrest-templates:1.1.2j
            name: caddy-config
            volumeMounts:
              - mountPath: /config
                name: caddy-config
        volumes:
          - name: tls-cert
            secret:
              secretName: sslcert //TODO
          - name: sts-cert-volume
            secret:
              secretName: sts-public-cert
          - emptyDir: {}
            name: caddy-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: samltest
  namespace: gosidecars
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: telemed-test.rm.dk
      http:
        paths:
          - backend:
              serviceName: samltest
              servicePort: 8443
            path: /samltest/?(.*)
  tls:
    - hosts:
        - telemed-test.rm.dk
      secretName: sslcert
---
apiVersion: v1
kind: Service
metadata:
  name: samltest
  namespace: gosidecars
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https-proxy
  selector:
    app.kubernetes.io/instance: samltest
