name: Build Action - GoSecurityProtocol

on:
  push:
    branches: [ master ]
    pull_request: ~
    tags: 
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - uses: actions/checkout@v2

      # if below step is skipped this build is a tag build. Can be used for skipping other steps.
      - name: Is Tag Build
        id: tag
        if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Create docker network
        run: docker network create gosamlserviceprovider

      - name: Startup the testenvironment used by the integration tests
        run: docker-compose up -d
        working-directory: testgosamlserviceprovider
      
      - name: Check that KeyCloack is up
        run: sh ./waitforkeycloak.sh
        working-directory: testgosamlserviceprovider

      - name: Build Docker image
        run: docker build -t kvalitetsit/caddysamlprovider --network gosamlserviceprovider .

      - name: Create Release Notes
        uses: softprops/action-gh-release@v1
        if: ${{ steps.tag.conclusion != 'skipped' }}
        with:
          generate_release_notes: true